# Generated by Django 5.0.7 on 2024-08-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredients',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe_ingredients',
            old_name='recipie_id',
            new_name='recipe',
        ),
    ]
