# Generated by Django 5.0.7 on 2024-08-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredient_id_recipe_ingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='Recipe_Ingredients',
            new_name='Recipe_Ingredient',
        ),
    ]
