# Generated by Django 5.0.7 on 2024-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredients_ingredient_rename_recipes_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=1),
        ),
    ]
