# Generated by Django 5.0.7 on 2024-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='static/images/cookpot.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='measurement',
            field=models.CharField(choices=[('GRAMS', 'g'), ('PIECES', 'pieces'), ('ML', 'ml'), ('CUPS', 'cups'), ('AMOUNT', 'amount'), ('TEASPOONS', 'teaspoons'), ('TABLESPOONS', 'tablespoons'), ('WHOLE', 'whole')], default='GRAMS', max_length=20),
        ),
    ]
