# Generated by Django 5.0.7 on 2024-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_image_alter_recipe_ingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='static/images/cook_pot.jpg', upload_to='images/'),
        ),
    ]
