# Generated by Django 5.0.7 on 2024-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/home/james/programming/finalProject/mealsimages/cook_pot.jpg', upload_to='images/'),
        ),
    ]
