# Generated by Django 5.0.7 on 2024-08-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='/images/cook_pot.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='measurement',
            field=models.CharField(choices=[('GRAMS', 'g'), ('PIECES', 'pieces'), ('ML', 'ml'), ('CUPS', 'cups'), ('AMOUNT', 'amount'), ('TEASPOONS', 'teaspoons'), ('TABLESPOONS', 'tablespoons'), ('WHOLE', 'whole'), ('CANS', 'cans')], default='GRAMS', max_length=20),
        ),
    ]
