# Generated by Django 5.0.7 on 2024-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/images/cook_pot.jpg', upload_to='images/'),
        ),
    ]
