# Generated by Django 5.0.7 on 2024-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_cook_time_remove_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='measurement',
            field=models.CharField(choices=[('GRAMS', 'g'), ('PIECES', 'pieces'), ('ML', 'ml'), ('CUPS', 'cups'), ('AMOUNT', 'amount'), ('TEASPOONS', 'teaspoons'), ('TABLESPOONS', 'tablespoons'), ('PIECES', 'pieces'), ('WHOLE', 'whole'), ('CANS', 'cans')], default='GRAMS', max_length=20),
        ),
    ]
