# Generated by Django 5.0.7 on 2024-09-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_cook_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
