# Generated by Django 5.0.7 on 2024-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_cook_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='timeH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='timeM',
            field=models.IntegerField(default=0),
        ),
    ]
