# Generated by Django 5.0.7 on 2024-09-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
    ]
